-- First, remove the table if it exists
DROP TABLE IF EXISTS customers;

-- Create the table anew
CREATE TABLE customers (
  id INTEGER primary key generated by default as identity,
  customer_name TEXT,
  phone VARCHAR(30)
);

-- Insert some test data
-- Using a multi-row insert statement here
INSERT into customers (customer_name, phone)
VALUES
  ('Sam', '555-1234'),
  ('Ham', '555-4321'),
  ('Ram', '555-5678');